apiVersion: extensions/v1beta1  
kind: Deployment
metadata:
  name: blog-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: "gcr.io/blog-kubernetes/mad01.github.io:v1.2"
        ports:
        - containerPort: 4000
