baseURL = "https://qone.io/"
languageCode = "en-us"
title = "qone.io"

[params]
  author = "Alexander Brandstedt"
  description = "infrastructure // code // systems"

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    guessSyntax = true
    noClasses = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS"]
